const editorState={image:null,message:'',added:0,dirty:false};
function questionEditor(){return `<section class="page-heading"><p class="eyebrow">BUILD YOUR QUESTION POOL</p><h1>Add questions</h1><p>Add a multiple-choice question, with an optional diagram from your course slides. It will appear in the selected course and module.</p><p><b>After adding questions, click Export question bank.</b> This exports questions.json. To publish, upload that file to the GitHub repository and replace questions.json. New images are included in the export. Changes here are local until published.</p></section><div class="editor-actions"><button class="primary" id="editor-export">Export question bank</button><span id="editor-status" role="status">${escape(editorState.message||`${editorState.added} questions added this session`)}</span></div><form id="question-editor" class="question-editor"><label>Course<select id="editor-world" required>${bank.worlds.filter(w=>w.id!=='saca').map(w=>`<option value="${escape(w.id)}" ${w.id===selected?'selected':''}>${escape(w.code+' · '+w.name)}</option>`).join('')}</select></label><label>Module / section<input id="editor-topic" list="editor-topics" required maxlength="160" placeholder="Choose an existing module or enter a new one"></label><datalist id="editor-topics"></datalist><label>Question<textarea id="editor-prompt" required maxlength="2000" rows="3" placeholder="What type of circuit is shown?"></textarea></label><fieldset><legend>Answer choices — select the correct answer</legend><p class="small">Enter 2–6 different choices. Select the circle beside the correct one.</p>${Array.from({length:6},(_,i)=>`<div class="editor-choice"><input type="radio" name="editor-correct" value="${i}" aria-label="Choice ${i+1} is correct" ${i===0?'checked':''}><input id="editor-choice-${i}" aria-label="Answer choice ${i+1}" maxlength="300" ${i<2?'required':''} placeholder="Choice ${i+1}${i>1?' (optional)':''}"></div>`).join('')}</fieldset><label>Explanation<textarea id="editor-explanation" required maxlength="2000" rows="3" placeholder="Explain why this answer is correct."></textarea></label><div class="editor-columns"><label>Source slide deck / sheet name<input id="editor-source" required maxlength="200" placeholder="C202 Electric Motor Controls.pdf"></label><label>Slide / page reference<input id="editor-page" required maxlength="160" placeholder="Page 72 · NAND"></label></div><label>Optional question image (PNG, JPEG or WebP; up to 5 MB)<input id="editor-image" type="file" accept="image/png,image/jpeg,image/webp"></label><p class="small">Choose the diagram from your slides. Crop out answer labels before attaching it.</p><div id="editor-image-preview"></div><button type="button" class="quiet" id="editor-remove-image">Remove image</button><p id="editor-error" role="alert"></p><button class="primary" type="submit" id="editor-add">Add to question pool</button></form>`;}
function makeEditorQuestion(data,image){
 const world=bank.worlds.find(w=>w.id===data.world&&w.id!=='saca');if(!world)throw Error('Choose a course.');
 for(const name of ['topic','prompt','explanation','source','page'])if(!data[name]?.trim())throw Error('Complete the module, question, explanation and source fields.');
 const options=data.choices.map(s=>s.trim()).filter(Boolean),answer=data.choices[data.correct]?.trim();
 if(options.length<2||options.length>6)throw Error('Enter between 2 and 6 answers.');
 if(new Set(options.map(s=>s.toLowerCase())).size!==options.length)throw Error('Answer choices must be different.');
 if(!answer)throw Error('Select a correct answer that has text.');
 if(image&&!/^data:image\/(png|jpeg|webp);base64,/.test(image))throw Error('Choose a PNG, JPEG or WebP image.');
 const id='custom-'+(globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(36).slice(2));
 return {id,world:world.id,topic:data.topic.trim(),type:image?'symbol':'quiz',prompt:data.prompt.trim(),answer,options,explanation:data.explanation.trim(),source:id,section:data.page.trim(),...(image?{diagram:{kind:'slide-image',imageKey:id,alt:'Course image for this question'}}:{}),custom:true};
}
function commitEditorQuestion(q,title,image){
 bank.sources[q.source]={title:title.trim()};bank.questions.push(q);bank.topics[q.world]??=[];if(!bank.topics[q.world].includes(q.topic))bank.topics[q.world].push(q.topic);
 const w=bank.worlds.find(w=>w.id===q.world);if(!w.sourceKeys.includes(q.source))w.sourceKeys.push(q.source);
 if(image){bank.slideImages??={};bank.slideImages[q.id]=image;}
 Object.assign(embeddedBank,JSON.parse(JSON.stringify(bank)));
 editorState.added++;editorState.dirty=true;editorState.image=null;editorState.message=`Added! ${editorState.added} added this session. Export question bank to keep your changes.`;
}
function editorExportHtml(sourceHtml,currentBank){
 const start='/*BANK_START*/\n',end='\n/*BANK_END*/',a=sourceHtml.indexOf(start),z=sourceHtml.indexOf(end,a+start.length);
 if(a<0||z<0)throw Error('Could not find the question bank in this file.');
 return sourceHtml.slice(0,a+start.length)+'\nconst embeddedBank='+JSON.stringify(currentBank).replace(/</g,'\\u003c')+';\n'+sourceHtml.slice(z);
}
function downloadEditedGuide(){try{const data=JSON.parse(JSON.stringify(bank));data.slideImages=Object.fromEntries(Object.entries(data.slideImages||{}).filter(([key])=>!originalImageKeys.has(key)));const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='questions.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);editorState.dirty=false;editorState.message='Exported questions.json. Upload it to your GitHub repository to publish. Scores are not included.';el('editor-status').textContent=editorState.message;}catch(e){el('editor-error').textContent=e.message;}}
function bindQuestionEditor(){if(screen!=='editor'||run)return;
 const updateTopics=()=>{el('editor-topics').innerHTML=(bank.topics[el('editor-world').value]||[]).map(t=>`<option value="${escape(t)}">`).join('');};updateTopics();el('editor-world').onchange=()=>{el('editor-topic').value='';updateTopics();};
 const showImage=()=>{el('editor-image-preview').innerHTML=editorState.image?`<figure class="slide-question-image"><img src="${editorState.image}" alt="Preview of attached question image"></figure>`:'';};showImage();
 el('editor-image').onchange=async e=>{const f=e.target.files[0];editorState.image=null;showImage();if(!f)return;const err=el('editor-error');err.textContent='';if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5*1024*1024){err.textContent='Choose a PNG, JPEG or WebP image smaller than 5 MB.';e.target.value='';return;}el('editor-add').disabled=true;try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read this image.'));r.readAsDataURL(f);});const im=new Image();im.src=data;await im.decode();editorState.image=data;showImage();}catch{err.textContent='This image could not be opened. Choose another image.';}finally{el('editor-add').disabled=false;}};
 el('editor-remove-image').onclick=()=>{editorState.image=null;el('editor-image').value='';showImage();};el('editor-export').onclick=downloadEditedGuide;
 el('question-editor').onsubmit=e=>{e.preventDefault();try{const data={world:el('editor-world').value,topic:el('editor-topic').value,prompt:el('editor-prompt').value,explanation:el('editor-explanation').value,source:el('editor-source').value,page:el('editor-page').value,choices:Array.from({length:6},(_,i)=>el('editor-choice-'+i).value),correct:Number(root.querySelector('input[name="editor-correct"]:checked').value)};const q=makeEditorQuestion(data,editorState.image);commitEditorQuestion(q,data.source,editorState.image);render();el('editor-world').value=q.world;updateTopics();el('editor-topic').value=q.topic;el('editor-source').value=data.source;el('editor-prompt').focus();}catch(error){el('editor-error').textContent=error.message;}};
}
window.addEventListener('beforeunload',e=>{if(editorState.dirty){e.preventDefault();e.returnValue='';}});
